version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  
  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pass123"
    ports:
      - "16543:80"
    depends_on:
      - db